# Generated by Django 3.2.9 on 2021-11-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_img/')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
            ],
            options={
                'verbose_name_plural': '1. Banners',
            },
        ),
    ]
