# Generated by Django 3.2.9 on 2021-11-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='article_img/')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banners'},
        ),
    ]
