# Generated by Django 3.2.9 on 2021-11-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoir', '0002_auto_20211124_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '2. Articles'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': '1. Banners'},
        ),
        migrations.AlterField(
            model_name='article',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
