# Generated by Django 3.2.9 on 2021-12-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoir', '0005_auto_20211201_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '5. Contacts'},
        ),
    ]
