# Generated by Django 3.2.9 on 2021-12-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoir', '0006_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ongoing_degree', models.CharField(max_length=300)),
                ('ongoing_institute', models.CharField(max_length=400)),
                ('degree', models.CharField(max_length=300)),
                ('institute', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': '3. Education',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '6. Contacts'},
        ),
    ]
