# Generated by Django 3.2.9 on 2021-12-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoir', '0009_alter_skill_percentage_of_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_url', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='project_img/')),
            ],
            options={
                'verbose_name_plural': '5. Projects',
            },
        ),
    ]
