# Generated by Django 3.2.9 on 2021-12-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoir', '0011_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(max_length=255)),
                ('social_media_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '7. Social media',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(),
        ),
    ]
